### PR TITLE
Rebuild to get ppc64le package

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

It seems the last build with ppc64le failed:
https://github.com/conda-forge/jasper-feedstock/runs/3897349272
I'd like to see if a new build is successful.  Needed for:
https://github.com/conda-forge/g2clib-feedstock/pull/26

closes #31

### CODE REVIEW

**Comment by xylar** [comment]
please rerender

**Comment by xylar** [comment]
I have switched both aarch64 and ppc64le to cross-compiling.  If you'd like me to just switch ppc64le (as in #31) I'd be glad to.

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@conda-forge/jasper, I'd appreciate your review.  Thanks very much!

**Review by akrherz — APPROVED** [review]

**Comment by akrherz** [comment]
Thanks @xylar , watching main branch CI now...

**Pull request merged**
