### PR TITLE
Aarch

### PR DESCRIPTION
**Pull request by hmaarrfk**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
Needs: https://github.com/conda-forge/freeglut-feedstock/pull/25

or: https://github.com/conda-forge/freeglut-feedstock/pull/24

**Comment by hmaarrfk** [comment]
After this gets merged, we should migrate from 1 to 2

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by hmaarrfk** [comment]
Thanks!

**Comment by isuruf** [comment]
@conda-forge/jasper, this is ready

**Pull request merged**
